site_name: draft docs
site_url: https://Kasper-Heliophysics-MDP.github.io/draft

nav:
  - Home: index.md
  - Code Reference:
    - utils: code_reference/utils.md
    - preprocessing: code_reference/preprocessing.md


theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: list